### ISSUE TITLE
Middleware unable to construct its own libhoney client

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/faraday-honeycomb#9]
It seems that at one point the initializer took a hash of `options` that could be used to construct an instance of `Libhoney`, but the initializer doesn't take this argument, so the fallback logic for creating a new libhoney client always fails:

https://github.com/honeycombio/faraday-honeycomb/blob/70917d213b0af57c6c2360ad19c3477b54f29130/lib/faraday/honeycomb/middleware.rb#L23-L24

**Comment by martin308** [comment]
This should be resolved in `v1.0.0` of the beeline! Please let us know over https://github.com/honeycombio/beeline-ruby/issues if not
